---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mysql
  namespace: ns-ip-alg
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~5.7
spec:
  releaseName: mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mysql
    version: 1.6.2
  values:
    image: mysql
    imageTag: 5.7.28
