---
# This secret should be stored in Git encrypted
# Sealed Secrets example: https://github.com/stefanprodan/gitops-helm#managing-kubernetes-secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: ns-ip-log
data:
  values.yaml: cGFzc3dvcmQ6IGFkbWlu
